# Generated by Django 4.2.23 on 2025-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='parking_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='parking_space',
            field=models.BooleanField(default=False),
        ),
    ]
