# Generated by Django 4.2.23 on 2025-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_unit_bathrooms_unit_bedrooms_unit_parking_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
